<a href="https://colab.research.google.com/github/serra-01/PythonNotes/blob/main/PyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
torch.__version__

'2.9.0+cpu'

In [ ]:
# Tensor
scalar = torch.tensor(5) # a multi-dimensional matrix containing elements of a single data type
scalar

tensor(5)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

5

In [ ]:
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[5, 5], [5, 5]])
MATRIX

tensor([[5, 5],
        [5, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[5, 5], [5, 5]]])
TENSOR.shape

torch.Size([1, 2, 2])

In [ ]:
random_tensor = torch.rand(1, 2, 4)
random_tensor

tensor([[[0.4693, 0.0748, 0.9234, 0.3963],
         [0.5046, 0.5625, 0.2892, 0.1429]]])

In [ ]:
random_image_tensor = torch.rand(size=(224, 224, 3))

In [ ]:
zero = torch.zeros(size=(2, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size=(2, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype # data type

torch.float32

In [ ]:
one.size()

torch.Size([2, 4])

In [ ]:
one.shape

torch.Size([2, 4])

In [ ]:
one.device

device(type='cpu')

In [ ]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.zeros_like(torch.arange(1, 11, 2)) # same shape

tensor([0, 0, 0, 0, 0])

In [ ]:
torch.tensor([3.0, 6.0], dtype=torch.float16, # half precision
             device=None, # cpu, cuda
             requires_grad=False)

tensor([3., 6.], dtype=torch.float16)

In [ ]:
torch.tensor([3.0, 6.0], dtype=torch.float16, # half precision
             device=None, # cpu, cuda
             requires_grad=False).type(torch.float32).dtype

torch.float32

In [ ]:
torch.mul(torch.tensor([3, 6, 9]), 10)

tensor([30, 60, 90])

In [ ]:
torch.add(torch.tensor([3, 6, 9]), 10)

tensor([13, 16, 19])

In [ ]:
torch.matmul(torch.tensor([1, 2, 3]), torch.tensor([1, 2, 3]))

tensor(14)

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]]), torch.tensor([[1, 2, 3], [4, 5, 6]]).shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]]).T, torch.tensor([[1, 2, 3], [4, 5, 6]]).T.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

In [ ]:
torch.matmul(torch.tensor([[1, 2, 3], [4, 5, 6]]), torch.tensor([[1, 2, 3], [4, 5, 6]]).T)

tensor([[14, 32],
        [32, 77]])

In [ ]:
x = torch.arange(0, 101, 10)
x, x.dtype

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(100), tensor(100))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [ ]:
torch.sum(x), x.sum()

(tensor(550), tensor(550))

In [ ]:
x.argmin() # index 0

tensor(0)

In [ ]:
x.argmax() # index 10

tensor(10)

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x.reshape(3, 3), x.reshape(1, 9), x.reshape(9, 1)

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
x_copy = x.view(3, 3) # changing original x changes x_copy
# bcs a view of tensor shares the same memory as original
x_copy[:, 0] = 0
x_copy, x

(tensor([[0., 2., 3.],
         [0., 5., 6.],
         [0., 8., 9.]]),
 tensor([0., 2., 3., 0., 5., 6., 0., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x, x], dim=0)
x_stacked

tensor([[0., 2., 3., 0., 5., 6., 0., 8., 9.],
        [0., 2., 3., 0., 5., 6., 0., 8., 9.],
        [0., 2., 3., 0., 5., 6., 0., 8., 9.],
        [0., 2., 3., 0., 5., 6., 0., 8., 9.],
        [0., 2., 3., 0., 5., 6., 0., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [0., 0., 0., 0., 0.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [0., 0., 0., 0., 0.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [ ]:
torch.zeros(2, 1, 2, 1, 2).squeeze().size()

torch.Size([2, 2, 2])

In [ ]:
torch.tensor([[1, 2, 3]]).squeeze() # removes all single dimensions

tensor([1, 2, 3])

In [ ]:
torch.tensor([1, 2, 3]).unsqueeze(dim=0), torch.tensor([1, 2, 3]).unsqueeze(dim=0).shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [ ]:
torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=0), torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=0).shape

(tensor([[[1, 2],
          [3, 4]]]),
 torch.Size([1, 2, 2]))

In [ ]:
torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=1), torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=1).shape

(tensor([[[1, 2]],
 
         [[3, 4]]]),
 torch.Size([2, 1, 2]))

In [ ]:
torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=2), torch.tensor([[1, 2], [3, 4]]).unsqueeze(dim=2).shape

(tensor([[[1],
          [2]],
 
         [[3],
          [4]]]),
 torch.Size([2, 2, 1]))

In [ ]:
torch.rand(size=(224, 224, 3)).permute(2, 0, 1).shape

torch.Size([3, 224, 224])

In [ ]:
torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])[:, 1, :]

tensor([[4, 5, 6]])

In [ ]:
torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])[0, 0, :]

tensor([1, 2, 3])

In [ ]:
arr = np.arange(1., 10.)
tensor = torch.from_numpy(arr).type(torch.float32) # def float64
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
arr = arr + 10
arr, tensor

(array([11., 12., 13., 14., 15., 16., 17., 18., 19.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
numpy_tensor.dtype, tensor, numpy_tensor

(dtype('float32'),
 tensor([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [ ]:
torch.cuda.is_available()

False

In [ ]:
torch.cuda.device_count()

0